"use client";

import type { DesignTokens } from "@/logic/schema/tokens.types";
import type { CssVarEntry } from "@/app/components/theme-dashboard/types";
import styles from "@/app/components/theme-dashboard/themeDashboard.module.css";

type Props = {
  tokens: DesignTokens;
  filteredEntries: CssVarEntry[];
  inventoryQuery: string;
  copyLabel: string;
  onInventoryQueryChange: (query: string) => void;
  onCopy: () => Promise<void>;
};

export default function InventorySection({
  tokens,
  filteredEntries,
  inventoryQuery,
  copyLabel,
  onInventoryQueryChange,
  onCopy,
}: Props) {
  return (
    <section className={styles.panel}>
      <div className={styles.panelHead}>
        <h2>Token Inventory</h2>
        <p>Search and copy only what you need instead of scanning a raw dump.</p>
      </div>

      <div className={styles.inventoryToolbar}>
        <input
          type="search"
          placeholder="Filter by token name or value"
          value={inventoryQuery}
          onChange={(e) => onInventoryQueryChange(e.target.value)}
        />
        <button className="btn-neutral" type="button" onClick={onCopy}>
          {copyLabel}
        </button>
      </div>

      <div className={styles.inventoryGrid}>
        <div className={styles.inventoryCard}>
          <h4>Metadata</h4>
          <p>
            <strong>Neutral Tint:</strong> {tokens.colors.neutral.tint}
          </p>
          <p>
            <strong>Generated By:</strong> {tokens.meta.generatedBy}
          </p>
          <p>
            <strong>Method:</strong> {tokens.meta.method}
          </p>
          <p>
            <strong>Timestamp:</strong> {tokens.meta.timestamp}
          </p>
        </div>
        <div className={`${styles.inventoryCard} ${styles.inventoryCardExpanded}`}>
          <h4>CSS Variables ({filteredEntries.length})</h4>
          <div className={styles.cssVarList}>
            {filteredEntries.length > 0 ? (
              filteredEntries.map((entry) => (
                <div key={entry.name} className={styles.cssVarRow}>
                  <code>{entry.name}</code>
                  <span>{entry.value}</span>
                </div>
              ))
            ) : (
              <p className={styles.inventoryEmpty}>No tokens match your filter.</p>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
